"""update bookmark stats unique sum

Revision ID: 277156a8b937
Revises: b3f7b0e2c61b
Create Date: 2018-09-29 15:54:20.358098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '277156a8b937'
down_revision = 'b3f7b0e2c61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookmark_stats_ibfk_1', 'bookmark_stats', type_='foreignkey')
    op.drop_index('unique_bid_date', table_name='bookmark_stats')
    op.create_foreign_key(None, 'bookmark_stats', 'bookmark', ['id'], ['id'])
    op.drop_column('bookmark_stats', 'stat_date')
    op.drop_column('bookmark_stats', 'bid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark_stats', sa.Column('bid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('bookmark_stats', sa.Column('stat_date', sa.DATE(), nullable=False))
    op.drop_constraint(None, 'bookmark_stats', type_='foreignkey')
    op.create_foreign_key('bookmark_stats_ibfk_1', 'bookmark_stats', 'bookmark', ['bid'], ['id'])
    op.create_index('unique_bid_date', 'bookmark_stats', ['bid', 'stat_date'], unique=True)
    # ### end Alembic commands ###
