"""add doc

Revision ID: 292c3a65759b
Revises: 4c70d35de054
Create Date: 2018-11-02 18:42:25.788873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '292c3a65759b'
down_revision = '4c70d35de054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP()'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP() on update CURRENT_TIMESTAMP()'), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('author', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('tag', sa.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), server_default=sa.text('0'), nullable=False),
    sa.Column('read_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_doc_author'), 'doc', ['author'], unique=False)
    op.create_index(op.f('ix_doc_category'), 'doc', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_category'), table_name='doc')
    op.drop_index(op.f('ix_doc_author'), table_name='doc')
    op.drop_table('doc')
    # ### end Alembic commands ###
