"""Add: mm & mm stats

Revision ID: 4c70d35de054
Revises: 277156a8b937
Create Date: 2018-10-10 18:26:02.527397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c70d35de054'
down_revision = '277156a8b937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP()'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP() on update CURRENT_TIMESTAMP()'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('url', sa.VARCHAR(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('ori_url', sa.VARCHAR(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('type', sa.VARCHAR(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('info', sa.VARCHAR(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.VARCHAR(length=256), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_mm_name'), 'mm', ['name'], unique=False)
    op.create_index(op.f('ix_mm_url'), 'mm', ['url'], unique=False)
    op.create_table('mm_stats',
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP()'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP() on update CURRENT_TIMESTAMP()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('click', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('like', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dislike', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['mm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mm_stats')
    op.drop_index(op.f('ix_mm_url'), table_name='mm')
    op.drop_index(op.f('ix_mm_name'), table_name='mm')
    op.drop_table('mm')
    # ### end Alembic commands ###
