"""add bookmark stats

Revision ID: b3f7b0e2c61b
Revises: b6df631342ed
Create Date: 2018-09-28 14:34:01.794911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f7b0e2c61b'
down_revision = 'b6df631342ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP()'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP() on update CURRENT_TIMESTAMP()'), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('click', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('like', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dislike', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['bid'], ['bookmark.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bid', 'stat_date', name='unique_bid_date'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark_stats')
    # ### end Alembic commands ###
