"""add bookmark info

Revision ID: b6df631342ed
Revises: 86495988bdb6
Create Date: 2018-09-28 11:35:29.580865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6df631342ed'
down_revision = '86495988bdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('info', sa.VARCHAR(length=100), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'info')
    # ### end Alembic commands ###
