"""add mv & mv stats

Revision ID: bd0fce49a194
Revises: 292c3a65759b
Create Date: 2018-11-27 15:50:10.848480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0fce49a194'
down_revision = '292c3a65759b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP()'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP() on update CURRENT_TIMESTAMP()'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('url', sa.VARCHAR(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('ori_url', sa.VARCHAR(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('download_url', sa.VARCHAR(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('cover_url', sa.VARCHAR(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('type', sa.VARCHAR(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('info', sa.VARCHAR(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.VARCHAR(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('duration', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('size', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('width', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('height', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_mv_name'), 'mv', ['name'], unique=False)
    op.create_index(op.f('ix_mv_url'), 'mv', ['url'], unique=False)
    op.create_table('mv_stats',
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP()'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP() on update CURRENT_TIMESTAMP()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('click', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('like', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dislike', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['mv.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mv_stats')
    op.drop_index(op.f('ix_mv_url'), table_name='mv')
    op.drop_index(op.f('ix_mv_name'), table_name='mv')
    op.drop_table('mv')
    # ### end Alembic commands ###
